import os
import json
import re
from typing import TypeVar, Type, Optional, Tuple
from pydantic import BaseModel
from dotenv import load_dotenv

from app.llm.prompts import SYSTEM_ROLE_PROMPT

load_dotenv()

# Define a type variable representing any BaseModel subclass
T = TypeVar('T', bound=BaseModel)

MAX_RETRIES = 2

from google import genai
from app.services.mongo_service import get_settings

# ── Dynamic settings fetchers ──
def _get_dynamic_settings():
    """Fetch settings from MongoDB, falling back to OS env vars."""
    mongo_settings = get_settings() or {}
    
    provider = mongo_settings.get("provider") or os.getenv("LLM_PROVIDER", "openrouter")
    default_model = "gemini-2.5-flash" if provider == "gemini" else "anthropic/claude-3-haiku"
    model = mongo_settings.get("model") or os.getenv("LLM_MODEL", default_model)
    context_size = int(mongo_settings.get("context_size") or os.getenv("CONTEXT_SIZE", "100000"))
    
    # Compile Gemini keys
    gemini_keys = [os.getenv("GEMINI_API_KEY")]
    
    # Add from MongoDB if configured
    if "gemini_keys" in mongo_settings and mongo_settings["gemini_keys"]:
        gemini_keys.extend(mongo_settings["gemini_keys"])
    # Add from env if configured
    elif os.getenv("GEMINI_ADDITIONAL_KEYS"):
        gemini_keys.extend([k.strip() for k in os.getenv("GEMINI_ADDITIONAL_KEYS").split(",")])
        
    gemini_keys = [k for k in gemini_keys if k] # Filter out None or empty
    
    # Remove duplicates but preserve order
    seen = set()
    unique_keys = []
    for k in gemini_keys:
        if k not in seen:
            seen.add(k)
            unique_keys.append(k)
            
    return provider, model, context_size, unique_keys

# In-memory index to preserve rotation state across API calls in the same worker
_current_key_idx = 0

def get_provider() -> str:
    p, _, _, _ = _get_dynamic_settings()
    return p

def get_model() -> str:
    _, m, _, _ = _get_dynamic_settings()
    return m

def get_context_size() -> int:
    _, _, c, _ = _get_dynamic_settings()
    return c

def _switch_gemini_key():
    global _current_key_idx
    _, _, _, keys = _get_dynamic_settings()
    if not keys:
        return False
    _current_key_idx = (_current_key_idx + 1) % len(keys)
    print(f"[Gemini] 🔄 Quota reached. Switching API Key to pool index {_current_key_idx + 1}/{len(keys)}")
    return True

# ── Collects detailed error messages for the current pipeline run ──
_error_log = []


def clear_error_log():
    """Clear error log at the start of each pipeline run."""
    global _error_log
    _error_log = []


def get_error_log() -> list:
    """Return collected error messages."""
    return list(_error_log)


def _classify_error(error: Exception) -> str:
    """
    Classify an API error into a human-readable message.
    Returns a clear, actionable error description.
    """
    err_str = str(error).lower()
    err_type = type(error).__name__

    if "429" in str(error) or "rate" in err_str or "quota" in err_str or "insufficient_quota" in err_str:
        return "API QUOTA EXCEEDED — You've hit the rate limit. Please wait a few minutes or add billing to your API account."
    elif "401" in str(error) or "authentication" in err_str or "invalid" in err_str and "key" in err_str:
        return "INVALID API KEY — The API key is incorrect or revoked. Please check your .env file."
    elif "403" in str(error) or "permission" in err_str or "forbidden" in err_str:
        return "ACCESS DENIED — Your API key doesn't have permission for this model."
    elif "404" in str(error) or "not found" in err_str:
        return "MODEL NOT FOUND — The requested AI model is unavailable. Check if the model name is correct."
    elif "timeout" in err_str or "timed out" in err_str:
        return "REQUEST TIMEOUT — The API server took too long to respond. Try again."
    elif "connection" in err_str or "network" in err_str:
        return "NETWORK ERROR — Could not connect to the API server. Check your internet connection."
    else:
        return f"API ERROR ({err_type}) — {str(error)[:200]}"


def clean_json_response(raw_text: str) -> str:
    """Strip markdown formatting and reasoning chunks from LLM raw JSON response."""
    # Strip <think>...</think> chunks commonly generated by DeepSeek-R1
    import re
    text = re.sub(r'<think>.*?</think>', '', raw_text, flags=re.DOTALL)
    
    text = text.strip()
    if text.startswith("```json"):
        text = text[len("```json"):].strip()
    elif text.startswith("```"):
        text = text[len("```"):].strip()
        
    if text.endswith("```"):
        text = text[:-len("```")].strip()
        
    # Optional regex cleaner to extract just the outermost {} or []
    # if there is surrounding conversational text.
    match = re.search(r'(\{.*\}|\[.*\])', text, re.DOTALL)
    if match:
        text = match.group(1)
        
    return text

def parse_with_pydantic(response_text: str, schema_class: Type[T]) -> T:
    """Parse string output to the declared pydantic schema"""
    cleaned_json = clean_json_response(response_text)
    try:
        data = json.loads(cleaned_json)
        return schema_class(**data)
    except Exception as e:
        print(f"Failed to parse JSON into {schema_class.__name__}: {e}")
        print(f"CLEANED TEXT: {cleaned_json}")
        raise e

# ═══════════════════════════════════════════
#  OPENROUTER PROVIDER
# ═══════════════════════════════════════════
def _call_openrouter(prompt: str, schema_class: Type[T]) -> Optional[T]:
    """Call OpenRouter API using the OpenAI SDK."""
    from openai import OpenAI

    load_dotenv(override=True)
    api_key = os.getenv("OPENROUTER_API_KEY")
    if not api_key:
        msg = "OpenRouter: API key not configured — add OPENROUTER_API_KEY to your .env file."
        print(f"[LLM] ERROR: {msg}")
        _error_log.append(msg)
        return None

    client = OpenAI(
        base_url="https://openrouter.ai/api/v1",
        api_key=api_key,
    )

    provider, model, _, _ = _get_dynamic_settings()
    
    for attempt in range(MAX_RETRIES + 1):
        print(f"[OpenRouter] Attempt {attempt + 1}/{MAX_RETRIES + 1} with model {model}...")
        try:
            response = client.chat.completions.create(
                model=model,
                messages=[
                    {"role": "system", "content": SYSTEM_ROLE_PROMPT},
                    {"role": "user", "content": prompt}
                ],
                temperature=0.0,
                max_tokens=15000,
                extra_body={"include_reasoning": False}
            )
            raw_response = response.choices[0].message.content
            print(f"[OpenRouter] RAW RESPONSE:\n{raw_response}\n---")
            parsed_data = parse_with_pydantic(raw_response, schema_class)
            return parsed_data
        except Exception as e:
            print(f"[OpenRouter] Failed on attempt {attempt + 1}: {e}")
            if attempt == MAX_RETRIES:
                error_msg = f"OpenRouter: {_classify_error(e)}"
                print(f"[OpenRouter] Max retries reached. Error: {error_msg}")
                _error_log.append(error_msg)
                return None
    return None

# ═══════════════════════════════════════════
# ═══════════════════════════════════════════
#  GEMINI IMPLEMENTATION
# ═══════════════════════════════════════════
def _call_gemini(prompt: str, schema_class: Type[T]) -> Optional[T]:
    global _current_key_idx
    provider, model, _, keys = _get_dynamic_settings()
    
    if not keys:
        print("[Gemini] ERROR: GEMINI_API_KEY not set.")
        return None

    full_prompt = f"{SYSTEM_ROLE_PROMPT}\n\n{prompt}\n\nOutput ONLY valid JSON matching the exact schema."
    
    # Allow extra retries based on how many backup keys we have
    max_attempts = MAX_RETRIES + len(keys)
    
    for attempt in range(max_attempts):
        # Always dynamically instantiate client to ensure we use the current rotated key
        idx = _current_key_idx % len(keys)
        gemini_client = genai.Client(api_key=keys[idx])
        
        try:
            response = gemini_client.models.generate_content(
                model=model,
                contents=full_prompt,
                config=genai.types.GenerateContentConfig(
                    response_mime_type="application/json"
                )
            )
            if not response.text:
                raise Exception("Empty response from Gemini")
            return parse_with_pydantic(response.text, schema_class)
        except Exception as e:
            err_str = str(e).lower()
            is_quota_error = "429" in err_str or "quota" in err_str or "rate limit" in err_str
            
            if is_quota_error and len(keys) > 1:
                _switch_gemini_key()
                continue # Retry immediately with new key
                
            print(f"[Gemini] Failed on attempt {attempt + 1}: {e}")
            if attempt >= max_attempts - 1:
                _error_log.append(f"Gemini: {_classify_error(e)}")
                return None
    return None

GLOBAL_CANCEL = False

def call_llm(prompt: str, schema_class: Type[T]) -> Optional[T]:
    """
    Unified LLM caller. Routes to either OpenRouter or Gemini.
    """
    global GLOBAL_CANCEL
    if GLOBAL_CANCEL:
        print("[LLM] ❌ LLM call aborted due to global cancel flag.")
        return None

    provider = get_provider()
    model = get_model()

    print(f"\n[LLM] Using provider: {provider.upper()} ({model})")
    if provider == "gemini":
        return _call_gemini(prompt, schema_class)
    else:
        return _call_openrouter(prompt, schema_class)
