import os
import json
import re
from typing import TypeVar, Type, Optional, Tuple
from pydantic import BaseModel
from dotenv import load_dotenv

from app.llm.prompts import SYSTEM_ROLE_PROMPT

load_dotenv()

# Define a type variable representing any BaseModel subclass
T = TypeVar('T', bound=BaseModel)

MAX_RETRIES = 2

import google.generativeai as genai

# ── Active provider state (can be changed at runtime via API) ──
_active_provider = os.getenv("LLM_PROVIDER", "openrouter")  # "openrouter" or "gemini"
_default_model = "gemini-2.5-flash" if _active_provider == "gemini" else "anthropic/claude-3-haiku"
_active_model = os.getenv("LLM_MODEL", _default_model)

# Configure Gemini if key exists
if os.getenv("GEMINI_API_KEY"):
    genai.configure(api_key=os.getenv("GEMINI_API_KEY"))

# ── Collects detailed error messages for the current pipeline run ──
_error_log = []

def get_provider() -> str:
    return _active_provider

def get_model() -> str:
    return _active_model

def set_provider(provider: str, model: Optional[str] = None):
    global _active_provider, _active_model
    if provider not in ["openrouter", "gemini"]:
        raise ValueError(f"Unknown provider: {provider}. Supported: 'openrouter', 'gemini'.")
    _active_provider = provider
    if model:
        _active_model = model
    print(f"[LLM] Provider switched to: {provider}, Model: {_active_model}")


def clear_error_log():
    """Clear error log at the start of each pipeline run."""
    global _error_log
    _error_log = []


def get_error_log() -> list:
    """Return collected error messages."""
    return list(_error_log)


def _classify_error(error: Exception) -> str:
    """
    Classify an API error into a human-readable message.
    Returns a clear, actionable error description.
    """
    err_str = str(error).lower()
    err_type = type(error).__name__

    if "429" in str(error) or "rate" in err_str or "quota" in err_str or "insufficient_quota" in err_str:
        return "API QUOTA EXCEEDED — You've hit the rate limit. Please wait a few minutes or add billing to your API account."
    elif "401" in str(error) or "authentication" in err_str or "invalid" in err_str and "key" in err_str:
        return "INVALID API KEY — The API key is incorrect or revoked. Please check your .env file."
    elif "403" in str(error) or "permission" in err_str or "forbidden" in err_str:
        return "ACCESS DENIED — Your API key doesn't have permission for this model."
    elif "404" in str(error) or "not found" in err_str:
        return "MODEL NOT FOUND — The requested AI model is unavailable. Check if the model name is correct."
    elif "timeout" in err_str or "timed out" in err_str:
        return "REQUEST TIMEOUT — The API server took too long to respond. Try again."
    elif "connection" in err_str or "network" in err_str:
        return "NETWORK ERROR — Could not connect to the API server. Check your internet connection."
    else:
        return f"API ERROR ({err_type}) — {str(error)[:200]}"


def clean_json_response(raw_text: str) -> str:
    """Strip markdown formatting and reasoning chunks from LLM raw JSON response."""
    # Strip <think>...</think> chunks commonly generated by DeepSeek-R1
    import re
    text = re.sub(r'<think>.*?</think>', '', raw_text, flags=re.DOTALL)
    
    text = text.strip()
    if text.startswith("```json"):
        text = text[len("```json"):].strip()
    elif text.startswith("```"):
        text = text[len("```"):].strip()
        
    if text.endswith("```"):
        text = text[:-len("```")].strip()
        
    # Optional regex cleaner to extract just the outermost {} or []
    # if there is surrounding conversational text.
    match = re.search(r'(\{.*\}|\[.*\])', text, re.DOTALL)
    if match:
        text = match.group(1)
        
    return text

def parse_with_pydantic(response_text: str, schema_class: Type[T]) -> T:
    """Parse string output to the declared pydantic schema"""
    cleaned_json = clean_json_response(response_text)
    try:
        data = json.loads(cleaned_json)
        return schema_class(**data)
    except Exception as e:
        print(f"Failed to parse JSON into {schema_class.__name__}: {e}")
        print(f"CLEANED TEXT: {cleaned_json}")
        raise e

# ═══════════════════════════════════════════
#  OPENROUTER PROVIDER
# ═══════════════════════════════════════════
def _call_openrouter(prompt: str, schema_class: Type[T]) -> Optional[T]:
    """Call OpenRouter API using the OpenAI SDK."""
    from openai import OpenAI

    load_dotenv(override=True)
    api_key = os.getenv("OPENROUTER_API_KEY")
    if not api_key:
        msg = "OpenRouter: API key not configured — add OPENROUTER_API_KEY to your .env file."
        print(f"[LLM] ERROR: {msg}")
        _error_log.append(msg)
        return None

    client = OpenAI(
        base_url="https://openrouter.ai/api/v1",
        api_key=api_key,
    )

    for attempt in range(MAX_RETRIES + 1):
        print(f"[OpenRouter] Attempt {attempt + 1}/{MAX_RETRIES + 1} with model {_active_model}...")
        try:
            response = client.chat.completions.create(
                model=_active_model,
                messages=[
                    {"role": "system", "content": SYSTEM_ROLE_PROMPT},
                    {"role": "user", "content": prompt}
                ],
                temperature=0.0,
                max_tokens=15000,
                extra_body={"include_reasoning": False}
            )
            raw_response = response.choices[0].message.content
            print(f"[OpenRouter] RAW RESPONSE:\n{raw_response}\n---")
            parsed_data = parse_with_pydantic(raw_response, schema_class)
            return parsed_data
        except Exception as e:
            print(f"[OpenRouter] Failed on attempt {attempt + 1}: {e}")
            if attempt == MAX_RETRIES:
                error_msg = f"OpenRouter: {_classify_error(e)}"
                print(f"[OpenRouter] Max retries reached. Error: {error_msg}")
                _error_log.append(error_msg)
                return None
    return None

# ═══════════════════════════════════════════
# ═══════════════════════════════════════════
#  GEMINI IMPLEMENTATION
# ═══════════════════════════════════════════
def _call_gemini(prompt: str, schema_class: Type[T]) -> Optional[T]:
    if not os.getenv("GEMINI_API_KEY"):
        print("[Gemini] ERROR: GEMINI_API_KEY not set.")
        return None

    full_prompt = f"{SYSTEM_ROLE_PROMPT}\n\n{prompt}\n\nOutput ONLY valid JSON matching the exact schema."
    model = genai.GenerativeModel(
        model_name=_active_model,
        generation_config={"response_mime_type": "application/json"}
    )
    for attempt in range(MAX_RETRIES):
        try:
            response = model.generate_content(full_prompt)
            if not response.text:
                raise Exception("Empty response from Gemini")
            return parse_with_pydantic(response.text, schema_class)
        except Exception as e:
            print(f"[Gemini] Failed on attempt {attempt + 1}: {e}")
            if attempt == MAX_RETRIES - 1:
                _error_log.append(f"Gemini: {_classify_error(e)}")
                return None
    return None

GLOBAL_CANCEL = False

def call_llm(prompt: str, schema_class: Type[T]) -> Optional[T]:
    """
    Unified LLM caller. Routes to either OpenRouter or Gemini.
    """
    global GLOBAL_CANCEL
    if GLOBAL_CANCEL:
        print("[LLM] ❌ LLM call aborted due to global cancel flag.")
        return None

    print(f"\n[LLM] Using provider: {_active_provider.upper()} ({_active_model})")
    if _active_provider == "gemini":
        return _call_gemini(prompt, schema_class)
    else:
        return _call_openrouter(prompt, schema_class)
